---

- hosts: all
  become: true
  tasks:

  - name: install apache2 and php packages
    package:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
  - name: Copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
